#!/bin/sh

set -eu

project_root() {
    CDPATH= cd -- "$(dirname -- "$0")/../.." && pwd
}

ensure_java_home() {
    if [ -n "${JAVA_HOME:-}" ] && [ -d "$JAVA_HOME" ]; then
        return 0
    fi

    if [ -x /usr/libexec/java_home ]; then
        if JAVA_HOME_CANDIDATE=$(/usr/libexec/java_home -v 21 2>/dev/null); then
            export JAVA_HOME="$JAVA_HOME_CANDIDATE"
            return 0
        fi
        if JAVA_HOME_CANDIDATE=$(/usr/libexec/java_home 2>/dev/null); then
            export JAVA_HOME="$JAVA_HOME_CANDIDATE"
            return 0
        fi
    fi

    for candidate in \
        /opt/homebrew/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home \
        /opt/homebrew/opt/openjdk/libexec/openjdk.jdk/Contents/Home \
        /usr/local/opt/openjdk@21/libexec/openjdk.jdk/Contents/Home \
        /usr/local/opt/openjdk/libexec/openjdk.jdk/Contents/Home
    do
        if [ -d "$candidate" ]; then
            export JAVA_HOME="$candidate"
            return 0
        fi
    done

    echo "JAVA_HOME is not set. Install JDK 21 and export JAVA_HOME." >&2
    exit 1
}

local_xcconfig_path() {
    printf "%s\n" "$(project_root)/iosApp/Configuration/Local.xcconfig"
}

write_local_xcconfig_from_env() {
    if [ -z "${IOS_TEAM_ID:-}" ] || [ -z "${IOS_BUNDLE_ID:-}" ]; then
        return 1
    fi

    config_file=$(local_xcconfig_path)
    app_name=${IOS_APP_NAME:-J3 Mobile}

    mkdir -p "$(dirname "$config_file")"
    cat > "$config_file" <<EOF
// Generated by scripts/ios.
TEAM_ID = ${IOS_TEAM_ID}
BUNDLE_ID = ${IOS_BUNDLE_ID}
APP_NAME = ${app_name}
EOF
}

ensure_local_xcconfig() {
    config_file=$(local_xcconfig_path)

    if [ -f "$config_file" ]; then
        return 0
    fi

    if write_local_xcconfig_from_env 2>/dev/null; then
        return 0
    fi

    echo "Missing iosApp/Configuration/Local.xcconfig. Copy Local.xcconfig.example or set IOS_TEAM_ID and IOS_BUNDLE_ID." >&2
    exit 1
}

prepare_auth_key_path() {
    if [ -n "${APP_STORE_CONNECT_API_KEY_PATH:-}" ] && [ -f "$APP_STORE_CONNECT_API_KEY_PATH" ]; then
        printf "%s\n" "$APP_STORE_CONNECT_API_KEY_PATH"
        return 0
    fi

    if [ -n "${APP_STORE_CONNECT_API_KEY_BASE64:-}" ] && [ -n "${APP_STORE_CONNECT_API_KEY_ID:-}" ]; then
        key_dir="$(project_root)/private_keys"
        key_path="${key_dir}/AuthKey_${APP_STORE_CONNECT_API_KEY_ID}.p8"
        mkdir -p "$key_dir"
        printf "%s" "$APP_STORE_CONNECT_API_KEY_BASE64" | base64 --decode > "$key_path"
        chmod 600 "$key_path"
        printf "%s\n" "$key_path"
        return 0
    fi

    return 1
}

default_marketing_version() {
    printf "%s\n" "0.1.0"
}

default_build_number() {
    date -u +%Y%m%d%H%M
}

internal_only_plist_value() {
    case "${IOS_INTERNAL_ONLY:-true}" in
        1|true|TRUE|yes|YES)
            printf "%s\n" "true"
            ;;
        *)
            printf "%s\n" "false"
            ;;
    esac
}
