name: iosApp
options:
  createIntermediateGroups: true
configs:
  Debug: debug
  Release: release
targets:
  iosApp:
    type: application
    platform: iOS
    deploymentTarget: "16.0"
    sources:
      - path: iosApp
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.j3mobile.iosApp
        INFOPLIST_FILE: iosApp/Info.plist
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(SRCROOT)/../composeApp/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/Frameworks"
    preBuildScripts:
      - name: Build ComposeApp Framework
        script: |
          cd "$SRCROOT/.."
          ./gradlew :composeApp:embedAndSignAppleFrameworkForXcode
    dependencies:
      - framework: $(SRCROOT)/../composeApp/build/xcode-frameworks/$(CONFIGURATION)/$(SDK_NAME)/ComposeApp.framework
        embed: true
        sign: true
